# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39181ba5c35694498dae7666ac4db3d6e7c027bd25a6b05f0f4ca8cbbe721398d4f91a2f4d6c38082a1eb191720a10d162ce533f6e00bbbd022dfe6925508e93

test:
  secret_key_base: 3904cb80a6ec5d460f21f7e6f2529c3607662e013915cda65e74fda54e7e8eee7481feeb7fc36a005996d9c1b55f3bee5a38291d15b21b5d054f91114c47340e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
